language: csharp
mono: none
dotnet: 2.0.3
sudo: false
cache:
  directories:
  - "$HOME/.nuget/"
before_install:
- set -e
addons:
  apt:
    packages:
    - dotnet-sharedframework-microsoft.netcore.app-1.1.2
script:
- "bash ./$CODEBASE/scripts/docker/build"
after_success:
- if [[ "$TRAVIS_BRANCH" == "master" ]]; then
    bash ./$CODEBASE/scripts/docker/publish;
  fi
